version: '{build}'

branches:
  except:
    - project/travis
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: x86
    qt: 5.9.7
    releaseName: github_qt59_vs2015_x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: x64
    qt: 5.9.7
    releaseName: github_qt59_vs2015_x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qt: 5.9.7
    releaseName: github_qt59_vs2017_x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: x64
    qt: 5.12
    releaseName: github_qt512_vs2015_x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qt: 5.12
    releaseName: github_qt512_vs2017_x64
before_build:
  - if "%platform%"=="x86" set QTDIR=C:\Qt\Qt5.9.7\5.9.7\msvc2015
  - if "%platform%"=="x64" set QTDIR=C:\Qt\Qt5.9.7\5.9.7\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - if "%platform%"=="x86" call D:\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86
  - if "%platform%"=="x64" call D:\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x64
build_script:
  - qmake
  - nmake
after_build:
  - if "%APPVEYOR_REPO_TAG%"=="true" windeployqt bin\HelloCI.exe --qmldir %QTDIR%\qml
artifacts:
  - path: bin
    name: $(releaseName)
deploy:
  provider: GitHub
  auth_token: $(GITHUB_OAUTH_TOKEN)
  description: 'github Release'
  draft: false
  prerelease: false
  on:
      APPVEYOR_REPO_TAG: true
